### ISSUE TITLE
Windows: Socket created with dyad_listen() won't take IPv4 connections

### ISSUE THREAD

**Issue by fatcerberus** [rxi/dyad#10]
Listening sockets are created with the AF_UNSPEC family flag, this causes an IPv6 socket to be returned on Windows systems supporting them.  As Windows has completely separate networking stacks for IPv4 and IPv6, the end result is that such sockets won't accept IPv4 connections, including local connections via loopback (127.0.0.1, or `localhost` which maps to the same).

The workaround I came up with was to pass in `AF_INET` for the socket family in `dyad_listenEx()`:
```c
  /* Get addrinfo */
  memset(&hints, 0, sizeof(hints));
  hints.ai_family = AF_INET;
  hints.ai_socktype = SOCK_STREAM;
  hints.ai_flags = AI_PASSIVE;
  sprintf(buf, "%d", port);
  err = getaddrinfo(host, buf, &hints, &ai);
```

However, this leads to the opposite problem: IPv6 clients can't connect.  Would there a way to support both protocols for listening sockets?

**Comment by rxi** [comment]
Take a look at issue #4.

If you want both IPv6 and IPv4 in this scenario you *may* be able to start two separate streams, pass them the same listener callbacks, and set them to listen on the same port: one with host `"0.0.0.0"` and one with `"::"`.

**Comment by fatcerberus** [comment]
Thanks, I wasn't aware there was a special host address for "listen on all", I thought the only way was to pass NULL to `dyad_listenEx()`.  I previously tried listening on `127.0.0.1` but that prevented remote connections.

I'll try the shared-callback trick and see what happens.

**Comment by fatcerberus** [comment]
Okay, opening two listen streams with the same accept callback seems to be working well, thanks. :smile:
