### ISSUE TITLE
How to reconnect?

### ISSUE THREAD

**Issue by bonfus** [rxi/dyad#15]
Sorry for this simple question, but I do not understand how to reconnect after a failure.
I tried a few combinations of `dyad_end` / `dyad_update` but it always fails.
(see example here [here](https://gist.github.com/bonfus/739ef2789e806208594596397fe7027e) )
The only way that seems to work is to create a new stream and reset the callback functions.
Is this the correct method?

`

**Comment by rxi** [comment]
> The only way that seems to work is to create a new stream and reset the callback functions.
Is this the correct method?

This is the correct method -- when a stream closes it is automatically destroyed ([DYAD_EVENT_DESTROY](https://github.com/rxi/dyad/blob/master/doc/api.md#dyad_event_destroy)) and its resources are freed, the stream is no longer valid and should not be used once this occurs.
